[package]
name = "tokei"
version = "0.1.0"
authors = ["Abdelhamid Bakhta <@starknet-io>"]
license = "MIT"
keywords = ["starknet", "vesting"]
description = "✨ 🐺 Starknet ERC20 token vesting smart contracts 💰⏳"
documentation = "https://github.com/starknet-io/tokei"
homepage = "https://github.com/starknet-io/tokei"
repository = "https://github.com/starknet-io/tokei"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.3.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.12.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }


[tool.snforge]
exit_first = false
