name: Test

on: [push, pull_request]

env:
  STARKNET_FOUNDRY_VERSION: 0.12.0
  STARKNET_FOUNDRY_VERSION: 0.12.0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.1"
      - name: Install starknet foundry
        run: |
          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh -s -- -v ${STARKNET_FOUNDRY_VERSION}
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Run cairo tests
        run: |
          export PATH="/root/.local/bin:$PATH"
          echo "Current PATH: $PATH"
          /root/.local/bin/snforge test || echo "snforge not found in /root/.local/bin"
